//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class subServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subServices()
        {
            this.itransIUServices = new HashSet<itransIUServices>();
        }
    
        public int subServiceId { get; set; }
        public Nullable<int> agentSubId { get; set; }
        public Nullable<int> subId { get; set; }
        public Nullable<int> serviceId { get; set; }
        public string serviceType { get; set; }
        public int count { get; set; }
        public int remain { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> createUserId { get; set; }
        public Nullable<int> updateUserId { get; set; }
    
        public virtual agentsSub agentsSub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itransIUServices> itransIUServices { get; set; }
        public virtual services services { get; set; }
        public virtual Sub Sub { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
